<?php $shipmentId = $this->getShipment()->getEntityId() ?>
<?php $entityC = $this->getC($shipmentId) ?>
<?php $entityA = $this->getA($shipmentId) ?>
<div id="eparcel-block" class="grid">
    <table>
        <tr class="headings">
            <th><?php echo $this->__('Label') ?></th>
            <th class="last"><?php echo $this->__('Value') ?></th>
        </tr>
        <tr>
            <td><?php echo $this->__('Charge Code') ?></td>
            <td>
                <?php $chargeCode = $entityC->getChargeCode() ?>
                <select class="charge-code" name="buzz_c[charge_code]">
                    <option <?php if ($chargeCode == 'x1') echo $this->__('selected') ?>
                        value="X1"><?php echo $this->__('X1') ?></option>
                    <option <?php if ($chargeCode == 's1') echo $this->__('selected') ?>
                        value="S1"><?php echo $this->__('S1') ?></option>
                    <option <?php if ($chargeCode == 'xs') echo $this->__('selected') ?>
                        value="XS"><?php echo $this->__('XS') ?></option>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->__('Weight') ?></td>
            <td><input class="required-entry" name="buzz_a[weight]" value="<?php echo $entityA->getWeight() ?>"
                       type="text"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Length') ?></td>
            <td><input class="buzz-length" name="buzz_a[length]" value="28" type="text"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Width') ?></td>
            <td><input class="buzz-width" name="buzz_a[width]" value="<?php echo $this->__($entityA->getWidth()) ?>" type="text"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Height') ?></td>
            <td><input class="buzz-height" name="buzz_a[height]" value="<?php echo $this->__($entityA->getHeight()) ?>" type="text"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Name') ?></td>
            <td><input class="required-entry" name="buzz_c[consignee_name]"
                       value="<?php echo $this->__($entityC->getConsigneeName()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Company Name') ?></td>
            <td><input name="buzz_c[consignee_company_name]" type="text" value="<?php echo $this->__($entityA->getConsigneeCompanyName()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Address Line 1') ?></td>
            <td><input name="buzz_c[consignee_address_line_1]"
                       value="<?php echo $this->__($entityA->getConsigneeAddressLine1()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Address Line 2') ?></td>
            <td><input name="buzz_c[consignee_address_line_2]"
                       value="<?php echo $this->__($entityC->getConsigneeAddressLine2()) ?>"></td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Consignee Address Line 3') ?></td>
            <td><input name="buzz_c[consignee_address_line_3]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeAddressLine3()) ?>"></td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Consignee Address Line 4') ?></td>
            <td><input name="buzz_c[consignee_address_line_4]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeAddressLine4()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Suburb') ?></td>
            <td><input name="buzz_c[consignee_suburb]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeSuburb()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee State') ?></td>
            <td><input name="buzz_c[consignee_state]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeState()) ?>"
                       readonly></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Post code') ?></td>
            <td><input class="validate-digits" name="buzz_c[consignee_post_code]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneePostCode()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee Phone Number') ?></td>
            <td><input name="buzz_c[consignee_phone_number]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneePhoneNumber()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Consignee email address') ?></td>
            <td><input class="validate-email" name="buzz_c[consignee_email_address]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeEmailAddress()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Are goods dangerous?') ?></td>
            <td>
                <select name="buzz_a[are_goods_dangerous]">
                    <option <?php if($entityA->getAreGoodsDangerous() == 'Y') echo 'selected' ?> value="Y"><?php echo $this->__('Y') ?></option>
                    <option <?php if ($entityA->getAreGoodsDangerous() == 'N') echo 'selected' ?> value="N"><?php echo $this->__('N') ?></option>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->__('Insurance required?') ?></td>
            <td>
                <select class="insurance-required" name="buzz_a[insurance_required]">
                    <option <?php if ($entityA->getInsuranceRequired() == 'Y') echo 'selected' ?> value="Y"><?php echo $this->__('Y') ?></option>
                    <option <?php if ($entityA->getInsuranceRequired() == 'N') echo 'selected' ?> value="N"><?php echo $this->__('N') ?></option>
                </select>
            </td>
        </tr>
        <tr>
            <td><?php echo $this->__('Insurance amount') ?></td>
            <td><input class="insurance-amount" name="buzz_a[insurance_amount]" type="text" readonly value="<?php echo $this->__($entityA->getInsuranceAmount()) ?>"></td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Consignee country') ?></td>
            <td><input name="buzz_c[consignee_country]" type="text"
                       value="<?php echo $this->__($entityC->getConsigneeCountry()) ?>" readonly></td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Print phone number?') ?></td>
            <td><input name="buzz_c[print_phone_number]" type="text" value="<?php echo $this->__($entityC->getPrintPhoneNumber()) ?>" readonly></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Delivery Instructions') ?></td>
            <td><input name="buzz_c[delivery_instructions]" type="text" value="<?php echo $this->__($entityC->getDeliveryInstructions()) ?>"></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Signature Required?') ?></td>
            <td>
                <select name="buzz_c[signature_required]">
                    <option <?php if ($entityC->getSignatureRequired() == 'Y') echo $this->__('selected') ?> value="Y"><?php echo $this->__('Y') ?></option>
                    <option <?php if ($entityC->getSignatureRequired() == 'N') echo $this->__('selected') ?> value="N"><?php echo $this->__('N') ?></option>
                </select>
            </td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Save to address book?') ?></td>
            <td><input name="buzz_c[save_to_address_book]" type="text" value="Y" readonly></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Reference') ?></td>
            <td><input name="buzz_c[reference]" type="text" value="<?php echo $this->__($entityC->getReference()) ?>"
                       readonly></td>
        </tr>
        <tr style="display: none">
            <td><?php echo $this->__('Print Reference?') ?></td>
            <td><input name="buzz_c[print_reference]" type="text" value="Y" readonly></td>
        </tr>
        <tr>
            <td><?php echo $this->__('Track Advice') ?></td>
            <td><input name="buzz_c[track_advice]" type="text" value="<?php echo $this->__($entityC->getTrackAdvice()) ?>" readonly>
            </td>
        </tr>
        <tr style="display: none">
            <td><input name="buzz_order_id" type="text" value="<?php echo $this->__($entityC->getOrderId()) ?>"></td>
        </tr>
    </table>
    <div class="f-left">
        <?php echo $this->getChildHtml('save_eparcel_button') ?>
    </div>
</div>
<script type="text/javascript">

    function submitEparcel() {
        if (parcelForm.validate()) {
            var area = $('eparcel-block').parentNode;
            var url = '<?php echo $this->getSubmitUrl() ?>';
            if ($(area)) {
                var fields = $(area).select('input', 'select', 'textarea');
                var data = Form.serializeElements(fields, true);
                url = url + (url.match(new RegExp('\\?')) ? '&isAjax=true' : '?isAjax=true');
                new Ajax.Request(url, {
                    parameters: $H(data),
                    loaderArea: area,
                    onSuccess: function (transport) {
                        try {
                            if (transport.responseText.isJSON()) {
                                var response = transport.responseText.evalJSON()
                                if (response.error) {
                                    alert(response.message);
                                }
                                if (response.ajaxExpired && response.ajaxRedirect) {
                                    setLocation(response.ajaxRedirect);
                                }
                            } else {
                                $(area).update(transport.responseText);
                            }
                            setLocation('<?php echo $_SERVER['HTTP_REFERER']; ?>');
                        }
                        catch (e) {
                            $(area).update(transport.responseText);
                        }
                    }
                });
            }
        }
    }

    if ($('save_eparcel_button')) {
        $('save_eparcel_button').observe('click', submitEparcel);
    }

    jQuery(document).ready(function () {
        jQuery('select.insurance-required').change(function () {
            if (jQuery(this).val() == 'Y') {
                jQuery('input.insurance-amount').prop('readonly', false);
            } else if (jQuery(this).val() == 'N') {
                jQuery('input.insurance-amount').prop('readonly', true);
            }
        });

        jQuery('.charge-code').change(function () {
            if (jQuery(this).val() == 'XS') {
                jQuery('.buzz-length').attr('value', '');
                jQuery('.buzz-width').attr('value', '');
                jQuery('.buzz-height').attr('value', '');
            }
        });
    });

    parcelForm = new varienForm('eparcel-block');
</script>